# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NoteApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NoteApp

pod 'KeychainAccess'
pod 'Alamofire'
pod 'CocoaDebug', :configurations => ['Debug']
pod "ToastViewSwift"

end
